job/urls.py
from django.contrib import admin
from django.urls import path , include
from account.views import activate
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
    path('', include('account.urls')),
    path('', include('letter.urls')),
    path('', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    path('activate/<uidb64>/<token>',
        activate, name='activate'),

    path('oauth/', include('social_django.urls', namespace='social')),


   path('password_reset_form/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset_form.html'
         ),
         name='password_reset'),
         
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()


from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager


JOB_TYPE = (
    ('1', "Full time"),
    ('2', "Part time"),
    ('3', "Internship"),
)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

class Job(models.Model):

    user = models.ForeignKey(User, related_name='User', on_delete=models.CASCADE) 
    title = models.CharField(max_length=300)
    description = RichTextField()
    tags = TaggableManager()
    location = models.CharField(max_length=300)
    job_type = models.CharField(choices=JOB_TYPE, max_length=1)
    category = models.ForeignKey(Category,related_name='Category', on_delete=models.CASCADE)
    salary = models.CharField(max_length=30, blank=True)
    company_name = models.CharField(max_length=300)
    company_description = RichTextField(blank=True, null=True)
    url = models.URLField(max_length=200)
    last_date = models.DateField()
    is_published = models.BooleanField(default=False)
    is_closed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)
    
    image = models.ImageField(default="")


    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)




    def __str__(self):
        return self.title
    




class Applicant(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)


    def __str__(self):
        return self.job.title


  

class BookmarkJob(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)


    def __str__(self):
        return self.job.title

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()


class PostView(models.Model):
    user =models.ForeignKey(User, on_delete=models.CASCADE)
    post =models.ForeignKey('Post',on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Post(models.Model):
    title = models.CharField(max_length=50)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    # comment_count = models.IntegerField(default=0)
    # view_count = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={
            'id': self.id
        })

    def get_update_url(self):
        return reverse('post-update',kwargs={
            'id': self.id
        })
    
    def get_delete_url(self):
        return reverse('post-detail',kwargs={
            'id': self.id
        })
        
    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    

account/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from account.models import User, Profile

GENDER_CHOICES = (
    ('male', 'Male'),
    ('female', 'Female'))


class EmployeeRegistrationForm(UserCreationForm):
    # gender = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=GENDER_CHOICES)

    def __init__(self, *args, **kwargs):
        super(EmployeeRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['gender'].required = True
        self.fields['first_name'].label = "First Name"
        self.fields['middle_name'].label = "Middle Name"
        self.fields['last_name'].label = "Last Name"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"

        # self.fields['gender'].widget = forms.CheckboxInput()

        self.fields['first_name'].widget.attrs.update(
            {
                'placeholder': 'Enter First Name',
            }
        )
        self.fields['middle_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Middle Name',
            }
        )
        self.fields['last_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Last Name',
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter Email',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Enter Password',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirm Password',
            }
        )

    class Meta:
        model = User
        fields = ['first_name', 'middle_name', 'last_name', 'email', 'password1', 'password2', 'gender']
        error_messages = {
            'first_name': {
                'required': 'First name is required',
                'max_length': 'Name is too long'
            },
            'middle_name': {
                'required': 'Middle name is required',
                'max_length': 'Middle Name is too long'
            },
            'last_name': {
                'required': 'Last name is required',
                'max_length': 'Last Name is too long'
            },
            'gender': {
                'required': 'Gender is required'
            }
        }

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if not gender:
            raise forms.ValidationError("Gender is required")
        return gender



    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.role = "employee"
        if commit:
            user.save()
        return user






class EmployerRegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(EmployerRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = "Company Name"
        self.fields['last_name'].label = "Company Address"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"

        self.fields['first_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Company Name',
            }
        )
        self.fields['last_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Company Address',
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter Email',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Enter Password',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirm Password',
            }
        )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        error_messages = {
            'first_name': {
                'required': 'First name is required',
                'max_length': 'Name is too long'
            },
            'last_name': {
                'required': 'Last name is required',
                'max_length': 'Last Name is too long'
            }
        }

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.role = "employer"
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password'})

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)

            if self.user is None:
                raise forms.ValidationError("User Does Not Exist.")
            if not self.user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not self.user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)

    def get_user(self):
        return self.user


class EmployeeProfileUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EmployeeProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {
                'placeholder': 'Enter First Name',
            }
        )
        self.fields['last_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Last Name',
            }
        )

    class Meta:
        model = User
        fields = ["first_name", "last_name", "gender"]



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

templates/cvbuilder/2_experience.html
{% if experiences %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center" id="heading2">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse2" aria-expanded="true" aria-controls="collapse3">
                <span style="font-size:1.3em;">
                    <i class="fas fa-briefcase mr-2"></i> Experiences
                </span>
            </button>
        </h3>
    </div>

     <div id="collapse2" class="collapse" aria-labelledby="heading2" data-parent="#accordion">

        <!-- Card Body -->
        <div class="card-body">

            <table class="table table-responsive-sm mb-0">
                
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">Title</th>
                        <th scope="col">Company</th>
                        <th scope="col">Duration</th>
                        <th scope="col">Skills</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <form id="orderingForm" method="post" action="{% url 'cvbuilder:SaveExperienceOrdering' %}"> {% csrf_token %}
                    
                    <tbody id="experiences">

                        {% for experience in experiences %}

                            <tr data-lookup="{{ experience.id }}">
                                <td><span class="handle_experiences handle"></span></td>                
                                <td>{{ experience.title }}</td>
                                <td>{{ experience.company }}</td>
                                <td>{{ experience.duration }}</td>
                                <td>
                                    {% if experience.tech_as_list %}
                                        {% for tech in experience.tech_as_list %}
                                            <span class="badge badge-primary badge-pill">{{ tech }}</span>
                                        {% endfor %}
                                    {% else %}
                                        No skill provided
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:UpdateExperience' experience.id %}">
                                        <div class="text-center text-success">
                                            <i class="far fa-edit"></i>
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'cvbuilder:DeleteExperience' experience.id %}">
                                        <div class="text-center text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </div>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                    </tbody>

                    <input type="hidden" id="orderingInput" name="ordering">
                </form>

            </table>
        </div>
    </div>
</div>

{% endif %}

templates/cvbuilder/3_skills.html
{% if skills %}

 <div class="card">
    <!-- Header -->
    <div class="card-header bg-dark text-center" id="heading3">
        <h3 class="mb-0">
            <button class="btn btn-link text-light" data-toggle="collapse" data-target="#collapse3" aria-expanded="true" aria-controls="collapse3">
                <span style="font-size:1.3em;">
                    <i class="fas fa-user-edit mr-1"></i>Skills
                </span>
            </button>
        </h3>
    </div>

    <div id="collapse3" class="collapse" aria-labelledby="heading3" data-parent="#accordion">
        <!-- Card Body -->
        <div class="card-body">
            <form id="skillsOrderingForm" method="post" action="{% url 'cvbuilder:SaveSkillsOrder' %}"> {% csrf_token %}
                <ul class="pl-0 pr-0 mb-0" style="white-space:nowrap;">
                    
                    <div id="skills" class="row">
                    {% for skill in skills %}

                        <li class="mb-2 mr-1" style="display:inline;" data-lookup="{{skill.id}}">
                            <span class="badge badge-light" style="font-size:1em; border:1px solid black;">
                                <i class="fas fa-grip-lines"></i>
                                {{ skill.title }}
                                <a href="{% url 'cvbuilder:DeleteSkill' skill.id %}" class="text-danger">
                                    <i class="fas fa-trash ml-1"></i>
                                </a>
                            </span>
                        </li>

                    {% endfor %}
                    </div>

                </ul>

                <input type="hidden" id="skillsOrderingInput" name="ordering">
            
            </form>
        </div>
    </div>
</div>

{% endif %}

templates/cvbuilder/7_script.html
{% load static %}

<script src="{% static 'cvbuilder/Sortable.min.js' %}"></script>

<script>

    // Template
    $('#id_template').addClass('form-control');

    // Name 
    $('#id_name').addClass('form-control');
    $('#id_name').attr("placeholder", "Name - Surname");
    // Email
    $('#id_email').addClass('form-control');
    $('#id_email').attr("placeholder", "Email Address");
    // Phone Number
    $('#id_telephone').addClass('form-control');
    $('#id_telephone').attr("placeholder", "Phone Number");
    // Linkedin Address
    $('#id_linkedin').addClass('form-control');
    $('#id_linkedin').attr("placeholder", "LinkedIn Address");
    // Github
    $('#id_github').addClass('form-control');
    $('#id_github').attr("placeholder", "Github Address");
    // Personal Website
    $('#id_website').addClass('form-control');
    $('#id_website').attr("placeholder", "Personal Website");
    // Primary Title
    $('#id_description').addClass('form-control');
    $('#id_description').attr("placeholder", "Primary Title");
    // Career Summary
    $('#id_career_summary').addClass('form-control');
    $('#id_career_summary').attr("placeholder", "Career Summary");
    // Default option
    $("option:contains('---------')").text("Select Resume Template");

// ---- Sortable for Experiences - if exists

    if($('#experiences').length){
        const groups = document.getElementById('experiences');
        let sortable = Sortable.create(groups, {
            handle: '.handle_experiences',
            onEnd: () => {
                saveExperienceOrder();
            }
        });
    }

    function saveExperienceOrder() {
        const rows = $('#experiences > tr');
        let ids = [];
        for (let row of rows) {
            ids.push(row.dataset.lookup);
        }
        $('#orderingInput').val(ids.join(','));
        $('#orderingForm').submit();
    }

// ---- Sortable for Skills - if exists

    if($('#skills').length){
        const skills = document.getElementById('skills');
        let skills_sortable = Sortable.create(skills, {
            onEnd: () => {
                saveSkillsOrder();
            }
        });
    }

    function saveSkillsOrder(){
        var skill_rows = $('#skills > li')
        var skill_ids = [];
        for(var row of skill_rows){
            skill_ids.push(row.dataset.lookup);
        };
        $('#skillsOrderingInput').val(skill_ids.join(','));
        $('#skillsOrderingForm').submit();
    }

// ---- Sortable for Education - if exists

    if($('#educations').length){
        const educations = document.getElementById('educations');
        let educations_sortable = Sortable.create(educations, {
            onEnd: () => {
                saveEducationOrder();
            }
        });
    };

    function saveEducationOrder(){
        var education_rows = $('#educations > tr');
        var education_ids = [];
        for(var row of education_rows){
            education_ids.push(row.dataset.lookup);
        };
        $('#educationOrderingInput').val(education_ids.join(','));
        $('#educationOrderingForm').submit();
    }

// ---- Sortable for Language - if exists

    if($('#languages').length){
        const languages = document.getElementById('languages');
        let languages_sortable = Sortable.create(languages, {
            onEnd: () => {
                saveLanguageOrder();
            }
        });
    };

    function saveLanguageOrder(){
        var language_rows = $('#languages > tr');
        var language_ids = [];
        for(var row of language_rows){
            language_ids.push(row.dataset.lookup);
        };
        $('#languageOrderingInput').val(language_ids.join(','));
        $('#languageOrderingForm').submit();
    }

// ---- Sortable for Achievement - if exists

    if($('#achievements').length){
        const achievements = document.getElementById('achievements');
        let achievements_sortable = Sortable.create(achievements, {
            onEnd: () => {
                saveAchiementOrder();
            }
        });
    };

    function saveAchiementOrder(){
        var achievement_rows = $('#achievements > tr');
        var achievement_ids = [];
        for(var row of achievement_rows){
            achievement_ids.push(row.dataset.lookup);
        };
        $('#achievementOrderingInput').val(achievement_ids.join(','));
        $('#achievementOrderingForm').submit();
    }

// ---- Sortable for Publication - if exists

    if($('#publications').length){
        const publications = document.getElementById('publications');
        let publications_sortable = Sortable.create(publications, {
            onEnd: () => {
                savePublicationOrder();
            }
        });
    };

    function savePublicationOrder(){
        var publication_rows = $('#publications > tr');
        var publication_ids = [];
        for(var row of publication_rows){
            publication_ids.push(row.dataset.lookup);
        };
        $('#publicationOrderingInput').val(publication_ids.join(','));
        $('#publicationOrderingForm').submit();
    }

</script>

templates/cvbuilder/crud_achievement.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Create/Edit Achievement {% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Achievement</b></label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label for="id_level" class="form-label"><b> Brief Description</b></label>
                {{ form.description }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the achievement');
        $('#id_description').addClass('form-control');
        $('#id_description').attr('placeholder', 'Provide a brief description if applicable');
        $('#id_description').css('height', '40');
    </script>

{% endblock%}

templates/cvbuilder/crud_experience.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Create or Edit Experience {% endblock %}
{% load static %}

{% block head_other %}

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <style> 
        .django-ckeditor-widget {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Job Title</b></label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label for="id_company" class="form-label"><b>Company Name</b></label>
                {{ form.company }}
            </div>

            <div class="mb-3">
                <label for="id_company" class="form-label"><b>Duration of Experience</b></label>
                {{ form.duration }}
            </div>

            <div class="mb-3">
                <label for="id_company" class="form-label"><b>Required Skills</b></label>
                {{ form.tech }}
            </div>

            <div class="mb-3">
                <label for="id_text" class="form-label"><b>Job Description</b></label>
                {{ form.text }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

   

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the job title');
        $('#id_company').addClass('form-control');
        $('#id_company').attr('placeholder', 'Provide the company name');
        $('#id_duration').addClass('form-control');
        $('#id_duration').attr('placeholder', 'Provide the duration -> May 2020 - Present');
        $('#id_tech').addClass('form-control');
        $('#id_tech').attr('placeholder', 'Provide skills separated by comma -> SAP,Personal Management,Workday,Bootstrap')
        $('#id_tech').css('height', '40');
    </script>

{% endblock%}

templates/cvbuilder/crud_language.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Create/Edit Language {% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Language</b></label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label for="id_level" class="form-label"><b>Level</b></label>
                {{ form.level }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the language');

        $('#id_level').addClass('form-control');
        $('#id_level').attr('placeholder', 'Provide the level -> Intermediate, Advanced');

    </script>

{% endblock%}

templates/cvbuilder/crud_publication.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Publication {% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Publication</b></label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label for="id_level" class="form-label"><b> Brief Description</b></label>
                {{ form.description }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the publication title');
        $('#id_description').addClass('form-control');
        $('#id_description').attr('placeholder', 'Provide a brief description (i.e. time, magazine) if applicable');
        $('#id_description').css('height', '40');
    </script>

{% endblock%}

templates/cvbuilder/crud_skill.html
{% extends "cvbuilder/_base.html" %}
{% block title %} Ozan Tellioglu | Create/Edit {% endblock %}
{% block header %} Create or Edit Skill {% endblock %}

{% block content %}

{% include 'cvbuilder/8_cv_navbar.html' %}

<div class="container-fluid text-center mt-3">    
  <div class="row content">
    <div class="col-sm-3"></div>

    <div class="col-sm-6 text-left"> 

        <form method="post">
                {% csrf_token %}

            <div class="mb-3">
                <label for="id_title" class="form-label"><b>Skill</b></label>
                {{ form.title }}
            </div>

            <input type="submit" class="btn btn-primary black-button-oz btn-block" value="Save">
        
        </form>

    </div>

    <div class="col-sm-3"></div>
  </div>
</div>

<div class="half-divider-oz"></div>

{% endblock %}

{% block script %}

    <script>
        $('#id_title').addClass('form-control');
        $('#id_title').attr('placeholder', 'Provide the skill name');
    </script>

{% endblock%}