account/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views  

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = "account"

urlpatterns = [
    path('employee/register/', RegisterEmployeeView.as_view(), name='employee-register'),
    
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    
    path('employer/register/', RegisterEmployerView.as_view(), name='employer-register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/urls.py
from django.contrib import admin
from django.urls import path , include
from account.views import activate
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
    path('', include('account.urls')),
    path('', include('letter.urls')),
    path('', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    path('activate/<uidb64>/<token>',
        activate, name='activate'),

    path('oauth/', include('social_django.urls', namespace='social')),


   path('password_reset_form/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset_form.html'
         ),
         name='password_reset'),
         
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/urls.py
from django.urls import path
from jobapp import views

from .import views
app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),

    path('about/', views.AboutUsView, name='about'),
    path('FAQ/', views.FAQ, name='FAQ'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    

    path('contact', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:id>/', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),


]

letter/urls.py
from django.urls import path
from . import views
app_name = "letter"

urlpatterns = [
    path('subscribe/', views.subscribe, name='subscribe'),
    path('mail_letter/', views.mail_letter, name='mail-letter')
]

posts/urls.py
from django.urls import path
from .import views
    

urlpatterns = [
    path('',views.index),
    
    path('blog/',views.blog,name='post-list'),

    path('post/<id>/',views.post,name='post-detail'),
    path('create/',views.post_create,name='post-create'),
    
    path('post/<id>/update/',views.post_update,name='post-update'),

    path('post/<id>/delete/',views.post_delete,name='post-delete'),
    
    path('search/', views.search, name='search'),

    

]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()


class PostView(models.Model):
    user =models.ForeignKey(User, on_delete=models.CASCADE)
    post =models.ForeignKey('Post',on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



class Post(models.Model):
    title = models.CharField(max_length=50)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    # comment_count = models.IntegerField(default=0)
    # view_count = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={
            'id': self.id
        })

    def get_update_url(self):
        return reverse('post-update',kwargs={
            'id': self.id
        })
    
    def get_delete_url(self):
        return reverse('post-detail',kwargs={
            'id': self.id
        })
        
    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    

posts/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail', 
        'categories', 'featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))
    class Meta:
        model = Comment
        fields = ('content', )

posts/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
from .models import Post,User,PostView
from django.db.models import Count,Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import CommentForm,PostForm

# Create your views here.
def get_user(user):
    qs = user.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None

def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'search_result.html', context)



def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset

    

def index(request):
    featured = Post.objects.filter(featured = True)
    latest = Post.objects.order_by('-timestamp')[0:3]

    if request.method == "POST":
        email = request.POST["email"]
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()

    context = {
        'object_list':featured,
        'latest':latest
    }
    return render(request,'index.html',context)



def blog(request):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)

    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)
    
    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count':category_count,
    }
    return render(request, 'blog.html', context)




def post(request, id):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post = get_object_or_404(Post, id=id)
    
    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=post)

    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': post.id
            }))
    context = {
        'post': post,
        'most_recent': most_recent,
        'category_count': category_count,
        'form': form
    }
    return render(request, 'post.html', context)

def post_create(request):
    title = 'Create'
    form = PostForm(request.POST or None, request.FILES or None)
    user = get_user(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = user
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "post_create.html", context)



def post_update(request,id):
    title = 'Update'
    post = get_object_or_404(Post, id=id)
    form = PostForm(
        request.POST or None,
        request.FILES or None,
        instance=post)
    user = get_user(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = user
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "post_create.html", context)
    
def post_delete(request):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect(reverse("post-list"))

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.first_name }},

Thank you for joing us. You are just one click away from getting connected to us.
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}


Please try resetting your password if the activation link shows "Activation link inavlid!!" error. In case of any other issues, please report to the department.


{% endautoescape %}

templates/base.html
<!DOCTYPE html>
<html>
      {% include 'head.html' %}
      <body id="top">
            {% include 'header.html' %}
            {% block content %}
            {% endblock content%}
            {% include 'footer.html' %}
            {% include 'scripts.html' %} 
            {% block extra_scripts %} {% endblock %}
      </body>
</html>

templates/footer.html
<footer class="site-footer">

	<a href="#top" class="smoothscroll scroll-top">
	  <span class="icon-keyboard_arrow_up"></span>
	</a>
  
	<div class="container">
	  <div class="row mb-5">
		
		<div class="col-6 col-md-3 mb-4 mb-md-0">

			<h4 class="webintern_footer_title h5"><small>Quick Links</small></h4>
			<ul class="webintern-footer-list">
			<li><a href="{% url 'jobapp:home' %}">Home</a></li>
			<li><a href="{% url 'jobapp:about' %}">About Us</a></li>
			<li><a href="{% url 'jobapp:contact' %}">Contact Us</a></li>
			</ul>

		</div>
		<div class="col-6 col-md-3 mb-4 mb-md-0">
      <h4 class="webintern_footer_title h5"><small>Support</small></h4>

		  <ul class="list-unstyled">
			<li><a href="{% url 'jobapp:privacy' %}">Privacy</a></li>
			<li><a href="{% url 'jobapp:terms' %}">Terms of Service</a></li>
		  </ul>
		</div>
		<div class="col-6 col-md-3 mb-4 mb-md-0">
      <h4 class="webintern_footer_title h5"><small>Contact Us</small></h4>
	  
		<i class="fa fa-map-marker" style="color: white !important;" aria-hidden="true"></i>
		<span style="color: white !important" > Itahari-1, Sunsari, Province No.1, Nepal</span>
		<br>
			<i class="fa fa-phone" style="color: white !important;" aria-hidden="true"></i>
			<span style="color: white !important;" >Phone:+977-9829325570, <br>+977 9825314955</span>

		  <div class="footer-social">
			<ul class="social-icons">
			<br>

				<a class="facebook" data-original-title="Facebook" data-toggle="tooltip" href="https://www.facebook.com/intourist/">
					<i class="fa fa-facebook"></i>
				  </a>
				  <a class="twitter" data-original-title="Twitter" data-toggle="tooltip" href="#">
					<i class="fa fa-twitter"></i>
				  </a>
				  <a class="instagram" data-original-title="Instagram" data-toggle="tooltip" href="#">
					<i class="fa fa-instagram"></i>
				  </a>
				  <a class="linkedin" data-original-title="linkedin" data-toggle="tooltip" href="https://www.linkedin.com/">
					<i class="fa fa-linkedin"></i>
				  </a>
			</ul>
		  </div>

		</div>
		<h4 class="  ml-2"><small><div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d228173.28470853186!2d87.1254569683946!3d26.673843040675607!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39ef6c66e80fbfa9%3A0x38094d1a7c974283!2sItahari!5e0!3m2!1sen!2snp!4v1642310904236!5m2!1sen!2snp" width="200" height="200" style="border-radius:25px;" allowfullscreen="" loading="lazy"></iframe></div>
		</small></h4>

	  </div>
  
	  <div class="col-xs-12 col-md-4 col-sm-6">
		<div class="marg-sm-b30"></div>
		<!-- webintern_footer_title -->
		<h4 class="webintern_footer_title h5"><small>Subscribe Newsletter</small></h4>
		<div class="empty-space marg-lg-b20"></div>
	  
		<!--
		<div class="simple-text last dark ">
		<p>Get latest updates and offers.</p>
		</div>
		-->
		
	  
		<a href="{% url 'letter:subscribe' %}" class="btn btn-warning btn-block btn-lg"><span class="text">JOIN US</span></a></a>
	   
	  <div class="row text-center">
		<div class="col-12">
		  <p class="copyright"><small>
			Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved  
		  </small></p>
		</div>
	  </div>
	</div>
  </footer>
  
  </div>
  
  
  
  <style>
  
  /*=================footer css start==============*/
  
  .text{
	font-weight: bolder !important;
	font-size: larger !important;
  }
  .webintern-footer {
	background: #0d2034;
	}
	
	.webintern-footer-inner {
	padding-top: 80px;
	padding-bottom: 50px;
	}
	
	.webintern-footer-logo {
	display: inline-block;
	}
	
	.webintern-footer .webintern-footer-inner .simple-text p {
	color: #fff;
	margin-top: 20px;
	margin-bottom: 15px;
	}
	.simple-text p {
	font-size: 15px;
	color: #42435d;
	font-family: 'Open Sans', sans-serif;
	font-weight: 400;
	line-height: 26px;
	margin-bottom: 0;
	}
	
	.webintern-footer .webintern-footer-inner .simple-text a {
	font-family: 'Open Sans', sans-serif;
	font-weight: 700;
	color: #f2c21a;
	font-size: 15px;
	}
	.footer-2 {
	padding-left: 55px;
	}
	.webintern_footer_title {
	margin-top: 0px;
	margin-bottom: 25px;
	}
	.webintern_footer_title small {
	font-family: 'Work Sans', sans-serif;
	color: #fff;
	font-weight: 700;
	font-size: 18px;
	text-transform: uppercase;
	}
	.webintern_footer_title:after {
	content: '';
	display: block;
	width: 30px;
	height: 2px;
	background: #f2c21a;
	margin-top: 15px;
	}
	.webintern-footer-list {
	padding: 0;
	}
	.webintern-footer-list li {
	margin-bottom: 17px;
	list-style: none;
	}
	.webintern-footer-list a {
	position: relative;
	font-size: 15px;
	line-height: 18px;
	color: #fff;
	padding-left: 0;
	letter-spacing: 0.20px;
	font-family: 'Open Sans', sans-serif;
	}
	.footer-3 {
	padding-left: 65px;
	
	}
	.webintern-footer-inner .simple-text.last {
	color: #d5d5d5;
	font-size: 17px;
	font-style: italic;
	font-family: 'Open Sans', sans-serif;
	font-weight: 400;
	}
	.tt-subscribe {
	position: relative;
	}
	.tt-subscribe input:not([type="submit"]) {
	width: 100%;
	height: 46px;
	background: #fff;
	font-size: 15px;
	color: #838486;
	padding-left: 20px;
	padding-right: 70px;
	border: 2px solid #fff;
	-moz-border-radius: 3px;
	border-radius: 3px;
	
	}
	.tt-subscribe-submit {
	background: #001b57;
	}
	
	.tt-subscribe-submit {
	position: absolute;
	top: 0;
	right: 0;
	width: 52px;
	height: 46px;
	font-size: 18px;
	line-height: 46px;
	color: #2a2a2a;
	text-align: center;
	background: #001b57;
	-moz-border-radius-topright: 3px;
	border-top-right-radius: 3px;
	-moz-border-radius-bottomright: 3px;
	border-bottom-right-radius: 3px;
	}
	
	
	.tt-subscribe-submit i.fa-envelope:before {
	content: "\f0e0";
	position: relative;
	z-index: 1;
	color: #fff;
	}
	.tt-subscribe-submit input {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background: #51658d;
	border: 0;
	}
	ul.tt-socail {
	padding: 0;
	margin-top: 30px;
	}
	.tt-socail li {
	display: inline-block;
	margin-right: 10px;
	}
	.tt-socail a {
	display: block;
	width: 36px;
	height: 36px;
	font-size: 17px;
	line-height: 34px;
	color: #fff;
	text-align: center;
	border: 1px solid #fff;
	-moz-border-radius: 100%;
	border-radius: 100%;
	}
	.webintern_footer_title small {
		font-family: 'Work Sans', sans-serif;
		color: #fff;
		font-weight: 700;
		font-size: 18px;
		text-transform: uppercase;
	}
	.tt-copy
	{
	font-size: 15px;
	line-height: 20px;
	color: #fff;
	background: #51658d;
	padding: 30px 0;
	font-family: 'Open Sans', sans-serif;
	}
	.tt-copy-right {
	text-align: right;
	}
	
	.social-icons
  {
	padding-left:0;
	margin-bottom:0;
	list-style:none
  }
  .social-icons li
  {
	display:inline-block;
	margin-bottom:4px
  }
  .social-icons li.title
  {
	margin-right:15px;
	text-transform:uppercase;
	color:#96a2b2;
	font-weight:700;
	font-size:13px
  }
  .social-icons a{
	background-color:#eceeef;
	color:#818a91;
	font-size:16px;
	display:inline-block;
	line-height:44px;
	width:44px;
	height:44px;
	text-align:center;
	margin-right:8px;
	border-radius:100%;
	-webkit-transition:all .2s linear;
	-o-transition:all .2s linear;
	transition:all .2s linear
  }
  .social-icons a:active,.social-icons a:focus,.social-icons a:hover
  {
	color:#fff;
	background-color:#29aafe
  }
  .social-icons.size-sm a
  {
	line-height:34px;
	height:34px;
	width:34px;
	font-size:14px
  }
  .social-icons a.facebook:hover
  {
	background-color:#3b5998
  }
  .social-icons a.twitter:hover
  {
	background-color:#00aced
  }
  .social-icons a.linkedin:hover
  {
	background-color:#007bb6
  }
  .social-icons a.dribbble:hover
  {
	background-color:#ea4c89
  }
  @media (max-width:767px)
  {
	.social-icons li.title
	{
	  display:block;
	  margin-right:0;
	  font-weight:600
	}
  }
  
	</style>

templates/header.html
{%load static%}
<div id="overlayer"></div>
<div class="loader">
  <div class="spinner-border text-primary" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>


<div class="site-wrap">

  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div> <!-- .site-mobile-menu -->

<style>
  .imgs{
    height: 80px !important;
    width: 100px !important;
    transition: transform 0.2s;


  }

  .imgs:hover{
    transform: scale(1.5);
    animation: zoom-in-zoom-out 5s ease-in infinite;
  }
  .egg{
font-size:14px !important;
font-weight: bold !important;
transition: transform 0.2s;

  }
  
.cur{
  transition: transform 0.2s;
  

}

  .cur:hover{
    transform: scale(1.5);
    animation: zoom-in-zoom-out 5s ease-in infinite;
  }

  @media only screen and (max-width: 768px) {
    /* For mobile phones: */
    [class*="acti"] {
      color: rgb(255, 255, 255) !important;
  

    }
  }

  
</style>

  <!-- NAVBAR -->
  <header class=" site-navbar  mt-3">
    <div class="container-fluid">
      <div class="row align-items-center">

        <div class="site-logo col-6" active><a href="{% url 'jobapp:home' %}">
          <div class="imgs">
            <img src="{% static 'images/loho23.png' %}" alt="Image"  class="img-fluid img-shadow">
          </div>
        
      </div>
        <nav class="ms-auto site-navigation ">
          <ul class="egg site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
            <li><a href="{% url 'jobapp:home' %}" class="cur nav-link active">🏠Home</a></li>
            <li><a href="{% url 'jobapp:about' %}" class="cur"><img src="{% static 'images/about.png' %}">About</a></li>
            <li><a href="{% url 'jobapp:job-list' %}" class="cur"><img src="{% static 'images/list.png' %}"> Job Listings</a></li>
            <li><a href="{% url 'jobapp:contact' %}" class="cur"><img src="{% static 'images/contactus.png' %}">Contact Us</a></li>

            <li class="has-children">
              <a href="#" class="cur">Pages</a>

              <ul class="dropdown">
                <li><a href="{%url 'jobapp:FAQ'%}"><img src="{% static 'images/faq.png' %}">  F A Q</a></li>
              </ul>

            </li> 
            
            <li><a href="{%url 'post-list'%}" class="cur"><img src="{% static 'images/blog.png' %}"> Blog</a></li>

          </ul>
        </nav>



        <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
          <div class="ml-auto">
            <div class="site-navigation fix">
              <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">

                {% if user.is_authenticated and user.role == 'employer'  %}
                <a href="{% url 'jobapp:create-job' %}"
                  class="js-clone-nav pr-3 btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span
                    class="mr-2 icon-add"></span>Post a Job</a>

                  
                    <li class="pr-3 has-children">
                      <a>Dashboard</a> 
                      <ul class="dropdown">
                        <li><a href="{% url 'jobapp:dashboard' %}">Dashboard</a></li>

                        <a href="{% url 'jobapp:applicants' 1 %}" class="dropdown-item">Applicants </a>
                        
                        <li><a href="{% url 'account:logout' %}">Logout</a></li>
                      </ul>
                    </li>

                {% elif user.is_authenticated and user.role == 'employee'  %}

                <li class="pr-3 has-children">
                  <a>Profile</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'account:employer-profile-update' %}">Edit Settings</a></li>
                  </ul>
                </li>

                <li class="pr-3 has-children">
                  <a>Dashboard</a> 
                  <ul class="dropdown">
                    <li><a href="{% url 'jobapp:dashboard' %}">Dashboard</a></li>
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                  </ul>
                </li>
                <!-- <a href="{% url 'account:logout' %}"
                class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                  class="mr-2 icon-lock_outline"></span>Log Out</a> -->
                {% else %}

                <li class="pr-3 has-children">
                  <a>Register</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'account:employer-register' %}"><img src="{% static 'images/company.png' %}">Employer</a></li>
                    <li><a href="{% url 'account:employee-register' %}"><img src="{% static 'images/employee.png' %}">Employee</a></li>
                  </ul>
                </li>

                <a href="{% url 'account:login' %}"
                  class="js-clone-nav btn btn-primary border-width-2 d-none d-lg-inline-block ov-fix"><span
                    class="mr-2 icon-lock_outline"></span>Log In</a>
                {% endif %}
              </ul>
            </div>

        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span
            class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>
    </div>
  </header>

templates/messages.html
{% if messages %}
{% for message in messages %}
  <div class="mb-5 alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

templates/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'make/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'make/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
  
    <link href='{% static "styles/github.css" %}' rel="stylesheet">
  </head>
  
<div class="col-4 offset-4 mb-5 mt-5">
<h3>{{ title }} an article</h3>
{{ form.media }}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>

</div>

{% endblock content %}

templates/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-hero overlay inner-page bg-image" style="background-image: url('{% static 'images/blog.jpg' %}');"  id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">The JobHub Blog🤔</h1>
          <div class="custom-breadcrumbs">
            <a href="{%url 'jobapp:home'%}" class="btn btn-outline-warning btn-sm "><span class="text" style="color: black !important;">Home</span></a></a>
            <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>BLOG </strong></span>
          </div>
        </div>
      </div>
    </div>
    
  </section>
<h2>This is the results of your search</h2>
{% for post in queryset %}
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    <br />
{% endfor %}

{% endblock %}